site_name: SpicyPhysics
site_description: A (barely almost) comprehensive physics notes repository.
site_url: https://moncherif979.github.io/spicyphysics/

theme:
  name: mkdocs
  features:
    - navigation.expand
    - navigation.sections
    - search.highlight
    - search.share
    - content.code.copy

repo_url: https://github.com/moncherif979/spicyphysics
repo_name: spicyphysics

nav:
  - Home: index.md
  - Formularies: formularies/index.md
  - Sources: sources/index.md
  - Notes:
      - Mechanics: notes/mechanics.md
      - Electromagnetism: notes/electromagnetism.md
      - Quantum: notes/quantum.md
      - Relativity: notes/relativity.md

